version: "3"

networks:
  backend:

volumes:
  tmp:

services:
  gate:
    hostname: gate
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app1
    ports:
      - "80:8080"
    networks:
      - backend
  app1:
    hostname: app1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18081:8080"
    networks:
      - backend
    volumes:
      - tmp:/volume