version: "3.3"

networks:
  backend:

services:
  gate:
    hostname: gate
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app1
      - app2
      - app3
    ports:
      - "8080:8080"
    networks:
      - backend
  app1:
    hostname: app1
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
  app2:
    hostname: app2
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
  app3:
    hostname: app3
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend