version: "3"

networks:
  backend:

volumes:
  tmp:

services:
  gate:
    environment:
      - id=0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - gate
    ports:
      - "18081:8080"
    networks:
      - backend
    volumes:
      - tmp:/volume