version: "3"

networks:
  test:

volumes:
  tmp:

services:
  app1:
    container_name: app1
    environment:
      - id=1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18081:8080"
    networks:
      - test
    volumes:
      - tmp:/volume
  app2:
    container_name: app2
    environment:
      - id=2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18082:8080"
    networks:
      - test
    volumes:
      - tmp:/volume