version: "3.8"

networks:
  backend:

services:
  gate:
    hostname: gate
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend
  app1:
    hostname: app1
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - gate
    ports:
      - "18081:8080"
    networks:
      - backend
  app2:
    hostname: app2
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app1
    ports:
      - "18082:8080"
    networks:
      - backend
  app3:
    hostname: app3
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app1
    ports:
      - "18083:8080"
    networks:
      - backend